name: smartpacifier_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:

  flutter:
    sdk: flutter

  # mDNS / service discovery (lets the ESP32 find the broker by name)
  nsd: ^5.0.1

  # MQTT
  mqtt_client: ^10.2.0

  # gRPC
  grpc: ^4.0.1

  # Protocol Buffers
  protobuf: ^4.0.0
  protobuf_google: ^1.0.0

  # Utilities
  yaml: ^3.1.2
  uuid: ^4.4.0
  path: ^1.9.0

  # File browser
  file_selector: ^1.0.3

  # Charts
  fl_chart:
    git:
      url: https://github.com/imaNNeo/fl_chart.git
      ref: main

  # Icons
  cupertino_icons: ^1.0.8

dev_dependencies:

  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

  # Proto generation
  protoc_builder: ^0.4.1
  build_runner: ^2.4.0

flutter:
  uses-material-design: true

  assets:
    - lib/screens/settings/configuration/config.yml