syntax = "proto3";

package Protos;

message IMUData {
  message MotionVector {
    float x = 1;
    float y = 2;
    float z = 3;
  }

  float temperature = 1;

  MotionVector acc = 2;   
  MotionVector gyro = 3;
}

message PPGData {
  message LedData {
    int32 led_1 = 1;
    int32 led_2 = 2;
    int32 led_3 = 3;
  }
  
  message TemperatureData {
    float temperature = 1;
  }
  
}

message AIRFLOWData{

  // Voltages in millivolts
  int32 voltage10k_l = 1;
  int32 voltage10k_r = 2;
  int32 voltage10k_e = 3;

  // Raw ADC codes
  uint32 raw_l = 4;
  uint32 raw_r = 5;
  uint32 raw_e = 6;

  // Computed temperatures in °C
  float temp_l = 7;
  float temp_r = 8;
  float temp_e = 9;
}


message TEMPERATUREData{
  message VoltageData{
    int32 voltage10k = 1;
    int32 voltage1k = 2;
  }
  
}


  message PTData {
    float temperature = 1;  
    float pressure    = 2; 
  }
  