syntax = "proto3";

package Protos;

message IMUData {
  message MotionVector {
    float x = 1;
    float y = 2;
    float z = 3;
  }

  float temperature = 1;

  MotionVector acc = 2;   
  MotionVector gyro = 3;
}

message PPGData {
  int32 sensor_id = 1;
  int32 led_1 = 2;
  int32 led_2 = 3;
  int32 led_3 = 4;

  float temperature = 5;
}

message AIRFLOWData{
  // computed temperatures
  float temp_l = 7;
  float temp_r = 8;
  float temp_e = 9;
}

message PTData {
    float temperature = 1;  
    float pressure    = 2; 
  }
  